### PR TITLE
Update genicam_camera_nodelet.cc

### PR DESCRIPTION
**Pull request by BrutusTT**
make frame_id accessible for custom names

### CODE REVIEW

**Comment by BrutusTT** [comment]
This fixes 2 issues:
1. namespace being required to work with tf2 otherwise one ends up with
`Warning: Invalid argument "/camera" passed ... tf2 frame_ids cannot start with a '/' `
2. frame_id can be something else than `camera`

**Comment by flixr** [comment]
Thanks for your PR!
Sound to me like it would make more sense to set the frame_id to just `camera` (instead of `/camera`) by default if it's running in the root namespace.
Adding the `frame_id` parameter still makes sense to set it to something else than `camera`...

**Comment by i-keller** [comment]
So basically, my problem is that I need to use a fixed frame_id that is coming from my stack. Sadly, I can't change the name. It would be nice to either set it directly through the launch file but getting it from the parameter server would work for me as well. Hence, the way I chose to go forward which should not impact any current way. Also, namespacing is not an option for me as well :(.

So, in the end, I don't mind any solution as long as I can rename it :). This was just the quickest that worked for me

**Comment by flixr** [comment]
We actually already did this in https://github.com/roboception/rc_genicam_camera/commit/2b23f32e0d69b03587dcf6f3a10609eb512d98a0 which I just pushed.
Closing this as it should work with the latest version.
If you still have problems you can reopen this issue.

**Comment by i-keller** [comment]
Great, should work for me, thanks

**Pull request closed without merging**
